/*
*  Classname : Iriss_Constants
*   Created By: Deloitte USI    
*   Created Date: 03-Mar-2014
*   Description: This class is used to store all the picklist value.
*   Version : 0.1 
*   Change Log
*   Version     Description                         Updated By
*    
*/
@isTest

public class IRIS_Constants{

    public static Final String SUBMISSION_STATUS_SUBMITTED = 'New';
    public static Final String SUBMISSION_STATUS_IN_PROGRESS = 'In Progress';
    public static Final String SUBMISSION_STATUS_AWAITING_TRANSLATION = 'Awaiting translation';
    public static Final String SUBMISSION_STATUS_PENDING_DECISION = 'Pending decision';
    public static Final String SUBMISSION_STATUS_APPROVED = 'Approved';
    public static Final String SUBMISSION_STATUS_REJECTED = 'Rejected';
    
    public static Final String SUBMISSION_DECISION_APPROVE = 'Approve';
    public static Final String SUBMISSION_DECISION_REJECT = 'Reject';
    
    public static Final String SUBMISSION_INTENDED_AUDIENCE_LOCAL = 'Local';
    public static Final String SUBMISSION_INTENDED_AUDIENCE_REGIONAL = 'Regional';
    public static Final String SUBMISSION_INTENDED_AUDIENCE_GLOBAL = 'Global';
    
    public static Final String SUBMISSION_ASSESSMENT_STATUS_IN_PROGRESS = 'In Progress';
    public static Final String SUBMISSION_ASSESSMENT_STATUS_COMPLETED = 'Completed';
    
    public static Final String PROFILE_AFFILIATE_NAME = 'Submission Affiliate Profile';
    public static Final String PROFILE_ASSESSOR_NAME = 'IRIS_Submission_Assessment_Profile';
    
    public static Final String IRIS = 'IRIS'; 
    public static Final String IRIS_SYSTEM_ADMIN = 'System Administrator';    

}